program ServidorGooPedir;

{$I FastMM4Options.inc}

uses
  Vcl.Forms,
  uMain in 'src\uMain.pas' {frmServidor},
  token in 'src\token\token.pas',
  util in 'src\util\util.pas',
  uDM in 'src\modulo\uDM.pas' {dm: TDataModule},
  token.autorizacao in 'src\token\token.autorizacao.pas',
  util.backup in 'src\util\util.backup.pas',
  Data.FireDACJSONReflect in 'src\other\Data.FireDACJSONReflect.pas',
  DataSet.Serialize.Config in 'src\other\DataSet.Serialize.Config.pas',
  DataSet.Serialize.Consts in 'src\other\DataSet.Serialize.Consts.pas',
  DataSet.Serialize.Export in 'src\other\DataSet.Serialize.Export.pas',
  DataSet.Serialize.Import in 'src\other\DataSet.Serialize.Import.pas',
  DataSet.Serialize.Language in 'src\other\DataSet.Serialize.Language.pas',
  DataSet.Serialize in 'src\other\DataSet.Serialize.pas',
  DataSet.Serialize.UpdatedStatus in 'src\other\DataSet.Serialize.UpdatedStatus.pas',
  DataSet.Serialize.Utils in 'src\other\DataSet.Serialize.Utils.pas',
  Horse.BasicAuthentication in 'src\other\Horse.BasicAuthentication.pas',
  Horse.Commons in 'src\other\Horse.Commons.pas',
  Horse.Constants in 'src\other\Horse.Constants.pas',
  Horse.Core.Group.Contract in 'src\other\Horse.Core.Group.Contract.pas',
  Horse.Core.Group in 'src\other\Horse.Core.Group.pas',
  Horse.Core in 'src\other\Horse.Core.pas',
  Horse.Core.Route.Contract in 'src\other\Horse.Core.Route.Contract.pas',
  Horse.Core.Route in 'src\other\Horse.Core.Route.pas',
  Horse.Core.RouterTree in 'src\other\Horse.Core.RouterTree.pas',
  Horse.Etag in 'src\other\Horse.Etag.pas',
  Horse.Exception in 'src\other\Horse.Exception.pas',
  Horse.HTTP in 'src\other\Horse.HTTP.pas',
  Horse.Jhonson in 'src\other\Horse.Jhonson.pas',
  Horse.JWT in 'src\other\Horse.JWT.pas',
  Horse.Paginate in 'src\other\Horse.Paginate.pas',
  Horse in 'src\other\Horse.pas',
  Horse.Proc in 'src\other\Horse.Proc.pas',
  Horse.Provider.Abstract in 'src\other\Horse.Provider.Abstract.pas',
  Horse.Provider.Apache in 'src\other\Horse.Provider.Apache.pas',
  Horse.Provider.CGI in 'src\other\Horse.Provider.CGI.pas',
  Horse.Provider.Console in 'src\other\Horse.Provider.Console.pas',
  Horse.Provider.Daemon in 'src\other\Horse.Provider.Daemon.pas',
  Horse.Provider.FPC.Apache in 'src\other\Horse.Provider.FPC.Apache.pas',
  Horse.Provider.FPC.CGI in 'src\other\Horse.Provider.FPC.CGI.pas',
  Horse.Provider.FPC.Daemon in 'src\other\Horse.Provider.FPC.Daemon.pas',
  Horse.Provider.FPC.FastCGI in 'src\other\Horse.Provider.FPC.FastCGI.pas',
  Horse.Provider.FPC.HTTPApplication in 'src\other\Horse.Provider.FPC.HTTPApplication.pas',
  Horse.Provider.ISAPI in 'src\other\Horse.Provider.ISAPI.pas',
  Horse.Provider.VCL in 'src\other\Horse.Provider.VCL.pas',
  Horse.WebModule in 'src\other\Horse.WebModule.pas' {HorseWebModule: TWebModule},
  JOSE.Builder in 'src\other\JOSE.Builder.pas',
  JOSE.Consumer in 'src\other\JOSE.Consumer.pas',
  JOSE.Consumer.Validators in 'src\other\JOSE.Consumer.Validators.pas',
  JOSE.Context in 'src\other\JOSE.Context.pas',
  JOSE.Core.Base in 'src\other\JOSE.Core.Base.pas',
  JOSE.Core.Builder in 'src\other\JOSE.Core.Builder.pas',
  JOSE.Core.JWA.Compression in 'src\other\JOSE.Core.JWA.Compression.pas',
  JOSE.Core.JWA.Encryption in 'src\other\JOSE.Core.JWA.Encryption.pas',
  JOSE.Core.JWA.Factory in 'src\other\JOSE.Core.JWA.Factory.pas',
  JOSE.Core.JWA in 'src\other\JOSE.Core.JWA.pas',
  JOSE.Core.JWA.Signing in 'src\other\JOSE.Core.JWA.Signing.pas',
  JOSE.Core.JWE in 'src\other\JOSE.Core.JWE.pas',
  JOSE.Core.JWK in 'src\other\JOSE.Core.JWK.pas',
  JOSE.Core.JWS in 'src\other\JOSE.Core.JWS.pas',
  JOSE.Core.JWT in 'src\other\JOSE.Core.JWT.pas',
  JOSE.Core.Parts in 'src\other\JOSE.Core.Parts.pas',
  JOSE.Encoding.Base64 in 'src\other\JOSE.Encoding.Base64.pas',
  JOSE.Hashing.HMAC in 'src\other\JOSE.Hashing.HMAC.pas',
  JOSE.OpenSSL.Headers in 'src\other\JOSE.OpenSSL.Headers.pas',
  JOSE.Signing.Base in 'src\other\JOSE.Signing.Base.pas',
  JOSE.Signing.ECDSA in 'src\other\JOSE.Signing.ECDSA.pas',
  JOSE.Signing.RSA in 'src\other\JOSE.Signing.RSA.pas',
  JOSE.Types.Arrays in 'src\other\JOSE.Types.Arrays.pas',
  JOSE.Types.Bytes in 'src\other\JOSE.Types.Bytes.pas',
  JOSE.Types.JSON in 'src\other\JOSE.Types.JSON.pas',
  JOSE.Types.Utils in 'src\other\JOSE.Types.Utils.pas',
  RESTRequest4D in 'src\other\RESTRequest4D.pas',
  RESTRequest4D.Request.Client in 'src\other\RESTRequest4D.Request.Client.pas',
  RESTRequest4D.Request.Contract in 'src\other\RESTRequest4D.Request.Contract.pas',
  RESTRequest4D.Response.Client in 'src\other\RESTRequest4D.Response.Client.pas',
  RESTRequest4D.Response.Contract in 'src\other\RESTRequest4D.Response.Contract.pas',
  RESTRequest4D.Response.Indy in 'src\other\RESTRequest4D.Response.Indy.pas',
  RESTRequest4D.Response.NetHTTP in 'src\other\RESTRequest4D.Response.NetHTTP.pas',
  RESTRequest4D.Utils in 'src\other\RESTRequest4D.Utils.pas',
  ThirdParty.Posix.Syslog in 'src\other\ThirdParty.Posix.Syslog.pas',
  Web.WebConst in 'src\other\Web.WebConst.pas',
  Horse.OctetStream in 'src\other\horse-octet-stream-master\src\Horse.OctetStream.pas',
  uSQL in 'src\sql\uSQL.pas',
  v2 in 'src\modulos\v2\v2.pas',
  uSite in 'src\uSite.pas',
  nfce in 'src\modulos\nfce\nfce.pas',
  uImportacaoProduto in 'src\uImportacaoProduto.pas',
  imprimir in 'src\modulos\impressao\imprimir.pas',
  PedidoSite in 'src\modulos\Controller\PedidoSite.pas',
  uToPedindo in 'src\importacao\uToPedindo.pas',
  GooPedirAPIController in 'src\controller\GooPedirAPIController.pas',
  Horse.XMLDoc in 'src\other\xml\Horse.XMLDoc.pas',
  uCacheControl in 'src\controller\uCacheControl.pas',
  uControllCaches in 'src\controller\uControllCaches.pas',
  Horse.ExceptionHandler in 'src\other\Horse.ExceptionHandler.pas',
  Horse.ServerStatic in 'src\other\horse-server-static-master\Horse.ServerStatic.pas',
  cors in 'src\modulo\cors.pas',
  uDadosWhatsapp in 'src\controller\uDadosWhatsapp.pas',
  PedidoController in 'src\modulos\Controller\PedidoController.pas',
  uMicroServices in 'src\modulo\uMicroServices.pas',
  conexao in 'src\modulo\conexao.pas',
  uInserirUpdate in 'src\modulos\Controller\uInserirUpdate.pas',
  uControlerProduto in 'src\controller\uControlerProduto.pas',
  uControllerSite in 'src\controller\uControllerSite.pas',
  uNewConsultas in 'src\modulos\uNewConsultas.pas',
  uAtualizacaoSite in 'src\controller\uAtualizacaoSite.pas',
  uGlobais in 'uGlobais.pas',
  uProcedure in 'src\procedure\uProcedure.pas',
  ProdutoQueue in 'src\modulos\Controller\ProdutoQueue.pas',
  Tasks in 'src\controller\Tasks.pas',
  TaskManager in 'src\controller\TaskManager.pas',
  uRelatorios in 'src\controller\uRelatorios.pas',
  Horse.Upload in 'src\other\horse-upload-master\src\Horse.Upload.pas',
  uControlerProdutoNotaFiscal in 'src\controller\uControlerProdutoNotaFiscal.pas' {$R *.res},
  System.SysUtils,
  uGenericaFuncion in 'src\util\uGenericaFuncion.pas',
  uTablet in 'src\tablet\uTablet.pas',
  uImageLocal in 'src\modulo\uImageLocal.pas',
  uCodigoPedidoDia in 'src\controller\uCodigoPedidoDia.pas',
  uIngredientesCardapio in 'src\controller\uIngredientesCardapio.pas',
  Horse.SocketIO.Functions in 'src\other\Horse.SocketIO.Functions.pas',
  Horse.SocketIO in 'src\other\Horse.SocketIO.pas',
  Horse.SocketIO.ServerSocket in 'src\other\Horse.SocketIO.ServerSocket.pas',
  GenericSocket.Client in 'src\other\GenericSocket.Client.pas',
  GenericSocket.Interfaces in 'src\other\GenericSocket.Interfaces.pas',
  GenericSocket.Message in 'src\other\GenericSocket.Message.pas',
  GenericSocket in 'src\other\GenericSocket.pas',
  GenericSocket.Server in 'src\other\GenericSocket.Server.pas',
  uTriggerManager in 'src\modulo\uTriggerManager.pas',
  uAgent in 'src\controller\uAgent.pas',
  FastMM4DataCollector in 'FastMM4DataCollector.pas',
  FastMM4LockFreeStack in 'FastMM4LockFreeStack.pas',
  FastMM4Messages in 'FastMM4Messages.pas',
  rota in 'src\rota\rota.pas',
  HashMemoria in 'HashMemoria.pas',
  Horse.Compression in 'src\other\Horse.Compression.pas',
  Horse.Compression.Types in 'src\other\Horse.Compression.Types.pas',
  uNFCe in 'uNFCe.pas',
  uTempoRotas in 'src\modulo\uTempoRotas.pas',
  financeiro in 'src\modulos\financeiro\financeiro.pas',
  uPerformanceMetrics in 'src\diagnostico\uPerformanceMetrics.pas',
  uFilaImpressao in 'src\modulos\impressao\uFilaImpressao.pas';

{$R *.res}


begin
//   ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  Application.CreateForm(TfrmServidor, frmServidor);
  Application.Run;

end.
